### ISSUE TITLE
FAQ of Parcel 2.x 

### ISSUE THREAD

**Issue by ntnyq** [ntnyq/parcel2-starter#1]
RT.

**Comment by ntnyq** [comment]
``` bash
🚨 @parcel/namer-default: Destination name index.js extension does not match bundle type "html"
Error: Destination name index.js extension does not match bundle type "html"
    at BundlerRunner.nameBundle (/Users/ntnyq/Desktop/github/npm/parcel2-starter/node_modules/@parcel/core/lib/BundlerRunner.js:192:19)
    at async Promise.all (index 0)
    at async BundlerRunner.nameBundles (/Users/ntnyq/Desktop/github/npm/parcel2-starter/node_modules/@parcel/core/lib/BundlerRunner.js:169:5)
    at async BundlerRunner.bundle (/Users/ntnyq/Desktop/github/npm/parcel2-starter/node_modules/@parcel/core/lib/BundlerRunner.js:132:5)
    at async Parcel.build (/Users/ntnyq/Desktop/github/npm/parcel2-starter/node_modules/@parcel/core/lib/Parcel.js:372:25)
    at async Parcel.run (/Users/ntnyq/Desktop/github/npm/parcel2-starter/node_modules/@parcel/core/lib/Parcel.js:253:18)
    at async Command.run (/Users/ntnyq/Desktop/github/npm/parcel2-starter/node_modules/parcel/lib/cli.js:155:7)
error Command failed with exit code 1.
```

**Comment by ntnyq** [comment]
``` bash
$ parcel build index.html
```

**Comment by ntnyq** [comment]
``` bash
$ parcel build index.html
```

Got an error

``` bash
🚨 @parcel/namer-default: Destination name index.js extension does not match bundle type "html"
Error: Destination name index.js extension does not match bundle type "html"
    at BundlerRunner.nameBundle (/Users/ntnyq/Desktop/github/npm/parcel2-starter/node_modules/@parcel/core/lib/BundlerRunner.js:192:19)
    at async Promise.all (index 0)
    at async BundlerRunner.nameBundles (/Users/ntnyq/Desktop/github/npm/parcel2-starter/node_modules/@parcel/core/lib/BundlerRunner.js:169:5)
    at async BundlerRunner.bundle (/Users/ntnyq/Desktop/github/npm/parcel2-starter/node_modules/@parcel/core/lib/BundlerRunner.js:132:5)
    at async Parcel.build (/Users/ntnyq/Desktop/github/npm/parcel2-starter/node_modules/@parcel/core/lib/Parcel.js:372:25)
    at async Parcel.run (/Users/ntnyq/Desktop/github/npm/parcel2-starter/node_modules/@parcel/core/lib/Parcel.js:253:18)
    at async Command.run (/Users/ntnyq/Desktop/github/npm/parcel2-starter/node_modules/parcel/lib/cli.js:155:7)
error Command failed with exit code 1.
```

[Links](https://github.com/parcel-bundler/parcel/issues/3500)
